"""remove page_number from chunks

Revision ID: 24266c1121a5
Revises: 0075353ef38a
Create Date: 2026-07-21 15:31:32.937359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24266c1121a5'
down_revision: Union[str, Sequence[str], None] = '0075353ef38a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chunks', 'page_number')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chunks', sa.Column('page_number', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
