"""add search_vector gin index

Revision ID: 450f13eab261
Revises: e3112b2632a2
Create Date: 2026-07-22 08:30:56.169432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '450f13eab261'
down_revision: Union[str, Sequence[str], None] = 'e3112b2632a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_chunks_search_vector', 'chunks', ['search_vector'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_chunks_search_vector', table_name='chunks', postgresql_using='gin')
    # ### end Alembic commands ###
